### ISSUE TITLE
[Question] An Makefile for start

### ISSUE THREAD

**Issue by Rarity0123** [tum-ei-eda/muriscv-nn#97]
Hi all,

Thank you for your dedication to developing this project. I noticed that version 0.1.0 is about to be released. However, after reading the README and scripts, and conducting some tests, I still couldn't figure out how to start correctly.

Could you please create a Makefile at the top level of the directory to streamline the process, especially after running the command:
git clone https://github.com/tum-ei-eda/muriscv-nn.git?

Thank you for your support!

Sincerely

**Comment by PhilippvK** [comment]
@Rarity0123 Sorry for the inconvenience and the late response due to the holidays.

Instead of Makefiles, we use the CMake build system. Further, we provide wrapper scripts to allow easy building and testing:

- [`Scripts/build.sh`](https://github.com/tum-ei-eda/muriscv-nn/blob/master/Scripts/build.sh).
- [`Scripts/unit_tests.sh`](https://github.com/tum-ei-eda/muriscv-nn/blob/master/Scripts/unit_tests.sh)
- [`Integration/tflm/run_tflm_integration_tests.sh`](https://github.com/tum-ei-eda/muriscv-nn/blob/master/Integration/tflm/run_tflm_integration_tests.sh)
- [`Integration/tflm_builtin/tflm_integration_tests.sh`](https://github.com/tum-ei-eda/muriscv-nn/blob/master/Integration/tflm_builtin/tflm_integration_tests.sh)
- [`Integration/tvm/run_tvm_integration_tests.sh`](https://github.com/tum-ei-eda/muriscv-nn/blob/master/Integration/tvm/run_tvm_integration_tests.sh)

Please note that not all dependencies will be downloaded automatically.

A good reference for example usage of the provided scripts are the CI jobs, i.e.:
- https://github.com/tum-ei-eda/muriscv-nn/blob/master/.github/workflows/build.yml
- https://github.com/tum-ei-eda/muriscv-nn/blob/master/.github/workflows/download_dependencies.yml
- https://github.com/tum-ei-eda/muriscv-nn/blob/master/.github/workflows/integration_tests.yml
- https://github.com/tum-ei-eda/muriscv-nn/blob/master/.github/workflows/unit_tests.yml

I just saw that something broke in the CI. I will take a look at this next week when I am back at my office.

I hope this helps, if you need further advice, feel free to re-open this issue.
